{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "9da673cc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting dlib==19.24.1\n",
      "  Using cached dlib-19.24.1.tar.gz (3.2 MB)\n",
      "  Preparing metadata (setup.py): started\n",
      "  Preparing metadata (setup.py): finished with status 'done'\n",
      "Building wheels for collected packages: dlib\n",
      "  Building wheel for dlib (setup.py): started\n",
      "  Building wheel for dlib (setup.py): finished with status 'error'\n",
      "  Running setup.py clean for dlib\n",
      "Failed to build dlib\n",
      "Installing collected packages: dlib\n",
      "  Running setup.py install for dlib: started\n",
      "  Running setup.py install for dlib: finished with status 'error'\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  error: subprocess-exited-with-error\n",
      "  \n",
      "  × python setup.py bdist_wheel did not run successfully.\n",
      "  │ exit code: 1\n",
      "  ╰─> [68 lines of output]\n",
      "      running bdist_wheel\n",
      "      running build\n",
      "      running build_py\n",
      "      running build_ext\n",
      "      C:\\Users\\saumy\\AppData\\Local\\Temp\\pip-install-7ke6dd0l\\dlib_7b3f7166a2ba41c8a368ccb7b749c114\\setup.py:129: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "        if LooseVersion(cmake_version) < '3.1.0':\n",
      "      Building extension for Python 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]\n",
      "      Invoking CMake setup: 'cmake C:\\Users\\saumy\\AppData\\Local\\Temp\\pip-install-7ke6dd0l\\dlib_7b3f7166a2ba41c8a368ccb7b749c114\\tools\\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\saumy\\AppData\\Local\\Temp\\pip-install-7ke6dd0l\\dlib_7b3f7166a2ba41c8a368ccb7b749c114\\build\\lib.win-amd64-cpython-39 -DPYTHON_EXECUTABLE=C:\\Users\\saumy\\Downloads\\anaconda\\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\saumy\\AppData\\Local\\Temp\\pip-install-7ke6dd0l\\dlib_7b3f7166a2ba41c8a368ccb7b749c114\\build\\lib.win-amd64-cpython-39 -A x64'\n",
      "      -- Building for: NMake Makefiles\n",
      "      CMake Error at CMakeLists.txt:5 (message):\n",
      "      \n",
      "      \n",
      "      \n",
      "        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
      "      \n",
      "      \n",
      "        You must use Visual Studio to build a python extension on windows.  If you\n",
      "        are getting this error it means you have not installed Visual C++.  Note\n",
      "        that there are many flavors of Visual Studio, like Visual Studio for C#\n",
      "        development.  You need to install Visual Studio for C++.\n",
      "      \n",
      "      \n",
      "        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
      "      \n",
      "      \n",
      "      \n",
      "      \n",
      "      -- Configuring incomplete, errors occurred!\n",
      "      Traceback (most recent call last):\n",
      "        File \"<string>\", line 2, in <module>\n",
      "        File \"<pip-setuptools-caller>\", line 34, in <module>\n",
      "        File \"C:\\Users\\saumy\\AppData\\Local\\Temp\\pip-install-7ke6dd0l\\dlib_7b3f7166a2ba41c8a368ccb7b749c114\\setup.py\", line 222, in <module>\n",
      "          setup(\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\__init__.py\", line 107, in setup\n",
      "          return distutils.core.setup(**attrs)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\core.py\", line 185, in setup\n",
      "          return run_commands(dist)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\core.py\", line 201, in run_commands\n",
      "          dist.run_commands()\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 969, in run_commands\n",
      "          self.run_command(cmd)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\dist.py\", line 1244, in run_command\n",
      "          super().run_command(command)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 988, in run_command\n",
      "          cmd_obj.run()\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\wheel\\bdist_wheel.py\", line 299, in run\n",
      "          self.run_command('build')\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\cmd.py\", line 318, in run_command\n",
      "          self.distribution.run_command(command)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\dist.py\", line 1244, in run_command\n",
      "          super().run_command(command)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 988, in run_command\n",
      "          cmd_obj.run()\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\command\\build.py\", line 131, in run\n",
      "          self.run_command(cmd_name)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\cmd.py\", line 318, in run_command\n",
      "          self.distribution.run_command(command)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\dist.py\", line 1244, in run_command\n",
      "          super().run_command(command)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 988, in run_command\n",
      "          cmd_obj.run()\n",
      "        File \"C:\\Users\\saumy\\AppData\\Local\\Temp\\pip-install-7ke6dd0l\\dlib_7b3f7166a2ba41c8a368ccb7b749c114\\setup.py\", line 134, in run\n",
      "          self.build_extension(ext)\n",
      "        File \"C:\\Users\\saumy\\AppData\\Local\\Temp\\pip-install-7ke6dd0l\\dlib_7b3f7166a2ba41c8a368ccb7b749c114\\setup.py\", line 171, in build_extension\n",
      "          subprocess.check_call(cmake_setup, cwd=build_folder)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\subprocess.py\", line 373, in check_call\n",
      "          raise CalledProcessError(retcode, cmd)\n",
      "      subprocess.CalledProcessError: Command '['cmake', 'C:\\\\Users\\\\saumy\\\\AppData\\\\Local\\\\Temp\\\\pip-install-7ke6dd0l\\\\dlib_7b3f7166a2ba41c8a368ccb7b749c114\\\\tools\\\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\\\Users\\\\saumy\\\\AppData\\\\Local\\\\Temp\\\\pip-install-7ke6dd0l\\\\dlib_7b3f7166a2ba41c8a368ccb7b749c114\\\\build\\\\lib.win-amd64-cpython-39', '-DPYTHON_EXECUTABLE=C:\\\\Users\\\\saumy\\\\Downloads\\\\anaconda\\\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\\\Users\\\\saumy\\\\AppData\\\\Local\\\\Temp\\\\pip-install-7ke6dd0l\\\\dlib_7b3f7166a2ba41c8a368ccb7b749c114\\\\build\\\\lib.win-amd64-cpython-39', '-A', 'x64']' returned non-zero exit status 1.\n",
      "      [end of output]\n",
      "  \n",
      "  note: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "  ERROR: Failed building wheel for dlib\n",
      "  error: subprocess-exited-with-error\n",
      "  \n",
      "  × Running setup.py install for dlib did not run successfully.\n",
      "  │ exit code: 1\n",
      "  ╰─> [83 lines of output]\n",
      "      running install\n",
      "      C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.\n",
      "      !!\n",
      "      \n",
      "              ********************************************************************************\n",
      "              Please avoid running ``setup.py`` directly.\n",
      "              Instead, use pypa/build, pypa/installer, pypa/build or\n",
      "              other standards-based tools.\n",
      "      \n",
      "              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.\n",
      "              ********************************************************************************\n",
      "      \n",
      "      !!\n",
      "        self.initialize_options()\n",
      "      running build\n",
      "      running build_py\n",
      "      running build_ext\n",
      "      C:\\Users\\saumy\\AppData\\Local\\Temp\\pip-install-7ke6dd0l\\dlib_7b3f7166a2ba41c8a368ccb7b749c114\\setup.py:129: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "        if LooseVersion(cmake_version) < '3.1.0':\n",
      "      Building extension for Python 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]\n",
      "      Invoking CMake setup: 'cmake C:\\Users\\saumy\\AppData\\Local\\Temp\\pip-install-7ke6dd0l\\dlib_7b3f7166a2ba41c8a368ccb7b749c114\\tools\\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\saumy\\AppData\\Local\\Temp\\pip-install-7ke6dd0l\\dlib_7b3f7166a2ba41c8a368ccb7b749c114\\build\\lib.win-amd64-cpython-39 -DPYTHON_EXECUTABLE=C:\\Users\\saumy\\Downloads\\anaconda\\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\saumy\\AppData\\Local\\Temp\\pip-install-7ke6dd0l\\dlib_7b3f7166a2ba41c8a368ccb7b749c114\\build\\lib.win-amd64-cpython-39 -A x64'\n",
      "      -- Building for: NMake Makefiles\n",
      "      CMake Error at CMakeLists.txt:5 (message):\n",
      "      \n",
      "      \n",
      "      \n",
      "        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
      "      \n",
      "      \n",
      "        You must use Visual Studio to build a python extension on windows.  If you\n",
      "        are getting this error it means you have not installed Visual C++.  Note\n",
      "        that there are many flavors of Visual Studio, like Visual Studio for C#\n",
      "        development.  You need to install Visual Studio for C++.\n",
      "      \n",
      "      \n",
      "        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
      "      \n",
      "      \n",
      "      \n",
      "      \n",
      "      -- Configuring incomplete, errors occurred!\n",
      "      Traceback (most recent call last):\n",
      "        File \"<string>\", line 2, in <module>\n",
      "        File \"<pip-setuptools-caller>\", line 34, in <module>\n",
      "        File \"C:\\Users\\saumy\\AppData\\Local\\Temp\\pip-install-7ke6dd0l\\dlib_7b3f7166a2ba41c8a368ccb7b749c114\\setup.py\", line 222, in <module>\n",
      "          setup(\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\__init__.py\", line 107, in setup\n",
      "          return distutils.core.setup(**attrs)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\core.py\", line 185, in setup\n",
      "          return run_commands(dist)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\core.py\", line 201, in run_commands\n",
      "          dist.run_commands()\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 969, in run_commands\n",
      "          self.run_command(cmd)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\dist.py\", line 1244, in run_command\n",
      "          super().run_command(command)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 988, in run_command\n",
      "          cmd_obj.run()\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\command\\install.py\", line 74, in run\n",
      "          return orig.install.run(self)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\command\\install.py\", line 697, in run\n",
      "          self.run_command('build')\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\cmd.py\", line 318, in run_command\n",
      "          self.distribution.run_command(command)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\dist.py\", line 1244, in run_command\n",
      "          super().run_command(command)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 988, in run_command\n",
      "          cmd_obj.run()\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\command\\build.py\", line 131, in run\n",
      "          self.run_command(cmd_name)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\cmd.py\", line 318, in run_command\n",
      "          self.distribution.run_command(command)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\dist.py\", line 1244, in run_command\n",
      "          super().run_command(command)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 988, in run_command\n",
      "          cmd_obj.run()\n",
      "        File \"C:\\Users\\saumy\\AppData\\Local\\Temp\\pip-install-7ke6dd0l\\dlib_7b3f7166a2ba41c8a368ccb7b749c114\\setup.py\", line 134, in run\n",
      "          self.build_extension(ext)\n",
      "        File \"C:\\Users\\saumy\\AppData\\Local\\Temp\\pip-install-7ke6dd0l\\dlib_7b3f7166a2ba41c8a368ccb7b749c114\\setup.py\", line 171, in build_extension\n",
      "          subprocess.check_call(cmake_setup, cwd=build_folder)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\subprocess.py\", line 373, in check_call\n",
      "          raise CalledProcessError(retcode, cmd)\n",
      "      subprocess.CalledProcessError: Command '['cmake', 'C:\\\\Users\\\\saumy\\\\AppData\\\\Local\\\\Temp\\\\pip-install-7ke6dd0l\\\\dlib_7b3f7166a2ba41c8a368ccb7b749c114\\\\tools\\\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\\\Users\\\\saumy\\\\AppData\\\\Local\\\\Temp\\\\pip-install-7ke6dd0l\\\\dlib_7b3f7166a2ba41c8a368ccb7b749c114\\\\build\\\\lib.win-amd64-cpython-39', '-DPYTHON_EXECUTABLE=C:\\\\Users\\\\saumy\\\\Downloads\\\\anaconda\\\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\\\Users\\\\saumy\\\\AppData\\\\Local\\\\Temp\\\\pip-install-7ke6dd0l\\\\dlib_7b3f7166a2ba41c8a368ccb7b749c114\\\\build\\\\lib.win-amd64-cpython-39', '-A', 'x64']' returned non-zero exit status 1.\n",
      "      [end of output]\n",
      "  \n",
      "  note: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "error: legacy-install-failure\n",
      "\n",
      "× Encountered error while trying to install package.\n",
      "╰─> dlib\n",
      "\n",
      "note: This is an issue with the package mentioned above, not pip.\n",
      "hint: See above for output from the failure.\n"
     ]
    }
   ],
   "source": [
    "pip install dlib==19.24.1\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "777ed0fb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting face_recognition\n",
      "  Using cached face_recognition-1.3.0-py2.py3-none-any.whl (15 kB)\n",
      "Requirement already satisfied: Pillow in c:\\users\\saumy\\downloads\\anaconda\\lib\\site-packages (from face_recognition) (9.2.0)\n",
      "Requirement already satisfied: face-recognition-models>=0.3.0 in c:\\users\\saumy\\downloads\\anaconda\\lib\\site-packages (from face_recognition) (0.3.0)\n",
      "Requirement already satisfied: numpy in c:\\users\\saumy\\downloads\\anaconda\\lib\\site-packages (from face_recognition) (1.21.5)\n",
      "Collecting dlib>=19.7\n",
      "  Using cached dlib-19.24.1.tar.gz (3.2 MB)\n",
      "  Preparing metadata (setup.py): started\n",
      "  Preparing metadata (setup.py): finished with status 'done'\n",
      "Requirement already satisfied: Click>=6.0 in c:\\users\\saumy\\downloads\\anaconda\\lib\\site-packages (from face_recognition) (8.0.4)\n",
      "Requirement already satisfied: colorama in c:\\users\\saumy\\downloads\\anaconda\\lib\\site-packages (from Click>=6.0->face_recognition) (0.4.5)\n",
      "Building wheels for collected packages: dlib\n",
      "  Building wheel for dlib (setup.py): started\n",
      "  Building wheel for dlib (setup.py): finished with status 'error'\n",
      "  Running setup.py clean for dlib\n",
      "Failed to build dlib\n",
      "Installing collected packages: dlib, face_recognition\n",
      "  Running setup.py install for dlib: started\n",
      "  Running setup.py install for dlib: finished with status 'error'\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  error: subprocess-exited-with-error\n",
      "  \n",
      "  × python setup.py bdist_wheel did not run successfully.\n",
      "  │ exit code: 1\n",
      "  ╰─> [68 lines of output]\n",
      "      running bdist_wheel\n",
      "      running build\n",
      "      running build_py\n",
      "      running build_ext\n",
      "      C:\\Users\\saumy\\AppData\\Local\\Temp\\pip-install-9ucffz_1\\dlib_272f9710072d44969dc97d7513527a81\\setup.py:129: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "        if LooseVersion(cmake_version) < '3.1.0':\n",
      "      Building extension for Python 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]\n",
      "      Invoking CMake setup: 'cmake C:\\Users\\saumy\\AppData\\Local\\Temp\\pip-install-9ucffz_1\\dlib_272f9710072d44969dc97d7513527a81\\tools\\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\saumy\\AppData\\Local\\Temp\\pip-install-9ucffz_1\\dlib_272f9710072d44969dc97d7513527a81\\build\\lib.win-amd64-cpython-39 -DPYTHON_EXECUTABLE=C:\\Users\\saumy\\Downloads\\anaconda\\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\saumy\\AppData\\Local\\Temp\\pip-install-9ucffz_1\\dlib_272f9710072d44969dc97d7513527a81\\build\\lib.win-amd64-cpython-39 -A x64'\n",
      "      -- Building for: NMake Makefiles\n",
      "      CMake Error at CMakeLists.txt:5 (message):\n",
      "      \n",
      "      \n",
      "      \n",
      "        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
      "      \n",
      "      \n",
      "        You must use Visual Studio to build a python extension on windows.  If you\n",
      "        are getting this error it means you have not installed Visual C++.  Note\n",
      "        that there are many flavors of Visual Studio, like Visual Studio for C#\n",
      "        development.  You need to install Visual Studio for C++.\n",
      "      \n",
      "      \n",
      "        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
      "      \n",
      "      \n",
      "      \n",
      "      \n",
      "      -- Configuring incomplete, errors occurred!\n",
      "      Traceback (most recent call last):\n",
      "        File \"<string>\", line 2, in <module>\n",
      "        File \"<pip-setuptools-caller>\", line 34, in <module>\n",
      "        File \"C:\\Users\\saumy\\AppData\\Local\\Temp\\pip-install-9ucffz_1\\dlib_272f9710072d44969dc97d7513527a81\\setup.py\", line 222, in <module>\n",
      "          setup(\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\__init__.py\", line 107, in setup\n",
      "          return distutils.core.setup(**attrs)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\core.py\", line 185, in setup\n",
      "          return run_commands(dist)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\core.py\", line 201, in run_commands\n",
      "          dist.run_commands()\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 969, in run_commands\n",
      "          self.run_command(cmd)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\dist.py\", line 1244, in run_command\n",
      "          super().run_command(command)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 988, in run_command\n",
      "          cmd_obj.run()\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\wheel\\bdist_wheel.py\", line 299, in run\n",
      "          self.run_command('build')\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\cmd.py\", line 318, in run_command\n",
      "          self.distribution.run_command(command)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\dist.py\", line 1244, in run_command\n",
      "          super().run_command(command)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 988, in run_command\n",
      "          cmd_obj.run()\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\command\\build.py\", line 131, in run\n",
      "          self.run_command(cmd_name)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\cmd.py\", line 318, in run_command\n",
      "          self.distribution.run_command(command)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\dist.py\", line 1244, in run_command\n",
      "          super().run_command(command)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 988, in run_command\n",
      "          cmd_obj.run()\n",
      "        File \"C:\\Users\\saumy\\AppData\\Local\\Temp\\pip-install-9ucffz_1\\dlib_272f9710072d44969dc97d7513527a81\\setup.py\", line 134, in run\n",
      "          self.build_extension(ext)\n",
      "        File \"C:\\Users\\saumy\\AppData\\Local\\Temp\\pip-install-9ucffz_1\\dlib_272f9710072d44969dc97d7513527a81\\setup.py\", line 171, in build_extension\n",
      "          subprocess.check_call(cmake_setup, cwd=build_folder)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\subprocess.py\", line 373, in check_call\n",
      "          raise CalledProcessError(retcode, cmd)\n",
      "      subprocess.CalledProcessError: Command '['cmake', 'C:\\\\Users\\\\saumy\\\\AppData\\\\Local\\\\Temp\\\\pip-install-9ucffz_1\\\\dlib_272f9710072d44969dc97d7513527a81\\\\tools\\\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\\\Users\\\\saumy\\\\AppData\\\\Local\\\\Temp\\\\pip-install-9ucffz_1\\\\dlib_272f9710072d44969dc97d7513527a81\\\\build\\\\lib.win-amd64-cpython-39', '-DPYTHON_EXECUTABLE=C:\\\\Users\\\\saumy\\\\Downloads\\\\anaconda\\\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\\\Users\\\\saumy\\\\AppData\\\\Local\\\\Temp\\\\pip-install-9ucffz_1\\\\dlib_272f9710072d44969dc97d7513527a81\\\\build\\\\lib.win-amd64-cpython-39', '-A', 'x64']' returned non-zero exit status 1.\n",
      "      [end of output]\n",
      "  \n",
      "  note: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "  ERROR: Failed building wheel for dlib\n",
      "  error: subprocess-exited-with-error\n",
      "  \n",
      "  × Running setup.py install for dlib did not run successfully.\n",
      "  │ exit code: 1\n",
      "  ╰─> [83 lines of output]\n",
      "      running install\n",
      "      C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.\n",
      "      !!\n",
      "      \n",
      "              ********************************************************************************\n",
      "              Please avoid running ``setup.py`` directly.\n",
      "              Instead, use pypa/build, pypa/installer, pypa/build or\n",
      "              other standards-based tools.\n",
      "      \n",
      "              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.\n",
      "              ********************************************************************************\n",
      "      \n",
      "      !!\n",
      "        self.initialize_options()\n",
      "      running build\n",
      "      running build_py\n",
      "      running build_ext\n",
      "      C:\\Users\\saumy\\AppData\\Local\\Temp\\pip-install-9ucffz_1\\dlib_272f9710072d44969dc97d7513527a81\\setup.py:129: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "        if LooseVersion(cmake_version) < '3.1.0':\n",
      "      Building extension for Python 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]\n",
      "      Invoking CMake setup: 'cmake C:\\Users\\saumy\\AppData\\Local\\Temp\\pip-install-9ucffz_1\\dlib_272f9710072d44969dc97d7513527a81\\tools\\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\saumy\\AppData\\Local\\Temp\\pip-install-9ucffz_1\\dlib_272f9710072d44969dc97d7513527a81\\build\\lib.win-amd64-cpython-39 -DPYTHON_EXECUTABLE=C:\\Users\\saumy\\Downloads\\anaconda\\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\saumy\\AppData\\Local\\Temp\\pip-install-9ucffz_1\\dlib_272f9710072d44969dc97d7513527a81\\build\\lib.win-amd64-cpython-39 -A x64'\n",
      "      -- Building for: NMake Makefiles\n",
      "      CMake Error at CMakeLists.txt:5 (message):\n",
      "      \n",
      "      \n",
      "      \n",
      "        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
      "      \n",
      "      \n",
      "        You must use Visual Studio to build a python extension on windows.  If you\n",
      "        are getting this error it means you have not installed Visual C++.  Note\n",
      "        that there are many flavors of Visual Studio, like Visual Studio for C#\n",
      "        development.  You need to install Visual Studio for C++.\n",
      "      \n",
      "      \n",
      "        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
      "      \n",
      "      \n",
      "      \n",
      "      \n",
      "      -- Configuring incomplete, errors occurred!\n",
      "      Traceback (most recent call last):\n",
      "        File \"<string>\", line 2, in <module>\n",
      "        File \"<pip-setuptools-caller>\", line 34, in <module>\n",
      "        File \"C:\\Users\\saumy\\AppData\\Local\\Temp\\pip-install-9ucffz_1\\dlib_272f9710072d44969dc97d7513527a81\\setup.py\", line 222, in <module>\n",
      "          setup(\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\__init__.py\", line 107, in setup\n",
      "          return distutils.core.setup(**attrs)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\core.py\", line 185, in setup\n",
      "          return run_commands(dist)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\core.py\", line 201, in run_commands\n",
      "          dist.run_commands()\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 969, in run_commands\n",
      "          self.run_command(cmd)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\dist.py\", line 1244, in run_command\n",
      "          super().run_command(command)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 988, in run_command\n",
      "          cmd_obj.run()\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\command\\install.py\", line 74, in run\n",
      "          return orig.install.run(self)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\command\\install.py\", line 697, in run\n",
      "          self.run_command('build')\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\cmd.py\", line 318, in run_command\n",
      "          self.distribution.run_command(command)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\dist.py\", line 1244, in run_command\n",
      "          super().run_command(command)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 988, in run_command\n",
      "          cmd_obj.run()\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\command\\build.py\", line 131, in run\n",
      "          self.run_command(cmd_name)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\cmd.py\", line 318, in run_command\n",
      "          self.distribution.run_command(command)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\dist.py\", line 1244, in run_command\n",
      "          super().run_command(command)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 988, in run_command\n",
      "          cmd_obj.run()\n",
      "        File \"C:\\Users\\saumy\\AppData\\Local\\Temp\\pip-install-9ucffz_1\\dlib_272f9710072d44969dc97d7513527a81\\setup.py\", line 134, in run\n",
      "          self.build_extension(ext)\n",
      "        File \"C:\\Users\\saumy\\AppData\\Local\\Temp\\pip-install-9ucffz_1\\dlib_272f9710072d44969dc97d7513527a81\\setup.py\", line 171, in build_extension\n",
      "          subprocess.check_call(cmake_setup, cwd=build_folder)\n",
      "        File \"C:\\Users\\saumy\\Downloads\\anaconda\\lib\\subprocess.py\", line 373, in check_call\n",
      "          raise CalledProcessError(retcode, cmd)\n",
      "      subprocess.CalledProcessError: Command '['cmake', 'C:\\\\Users\\\\saumy\\\\AppData\\\\Local\\\\Temp\\\\pip-install-9ucffz_1\\\\dlib_272f9710072d44969dc97d7513527a81\\\\tools\\\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\\\Users\\\\saumy\\\\AppData\\\\Local\\\\Temp\\\\pip-install-9ucffz_1\\\\dlib_272f9710072d44969dc97d7513527a81\\\\build\\\\lib.win-amd64-cpython-39', '-DPYTHON_EXECUTABLE=C:\\\\Users\\\\saumy\\\\Downloads\\\\anaconda\\\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\\\Users\\\\saumy\\\\AppData\\\\Local\\\\Temp\\\\pip-install-9ucffz_1\\\\dlib_272f9710072d44969dc97d7513527a81\\\\build\\\\lib.win-amd64-cpython-39', '-A', 'x64']' returned non-zero exit status 1.\n",
      "      [end of output]\n",
      "  \n",
      "  note: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "error: legacy-install-failure\n",
      "\n",
      "× Encountered error while trying to install package.\n",
      "╰─> dlib\n",
      "\n",
      "note: This is an issue with the package mentioned above, not pip.\n",
      "hint: See above for output from the failure.\n"
     ]
    }
   ],
   "source": [
    "pip install face_recognition"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "ce2a7a59",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'face_recognition'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp\\ipykernel_21096\\4236744526.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mcv2\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      2\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mnumpy\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0mnp\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 3\u001b[1;33m \u001b[1;32mimport\u001b[0m \u001b[0mface_recognition\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      4\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mos\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      5\u001b[0m \u001b[1;32mfrom\u001b[0m \u001b[0mdatetime\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mdatetime\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'face_recognition'"
     ]
    }
   ],
   "source": [
    "import cv2\n",
    "import numpy as np\n",
    "import face_recognition\n",
    "import os\n",
    "from datetime import datetime\n",
    "\n",
    "#Loading images using path\n",
    "path = 'Images'\n",
    "images = []\n",
    "names = []\n",
    "List = os.listdir(path)\n",
    "#print(List)\n",
    "\n",
    "for name in List:\n",
    "    img = cv2.imread(f'{path}/{name}')\n",
    "    images.append(img)\n",
    "    names.append(os.path.splitext(name)[0])\n",
    "\n",
    "#print(names)\n",
    "\n",
    "#Function to find encodings for all images in directory\n",
    "\n",
    "def encode(images):\n",
    "    encode_list = []\n",
    "    for img in images:\n",
    "        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)\n",
    "        encodeImg = face_recognition.face_encodings(img)[0]\n",
    "        encode_list.append(encodeImg)\n",
    "    return encode_list\n",
    "\n",
    "def record_attendance(name):\n",
    "    with open('attendancelist.csv', 'r+') as file:\n",
    "        List = file.readlines()\n",
    "        namelist = []\n",
    "\n",
    "        for line in List:\n",
    "            record = line.split(',')\n",
    "            namelist.append(record[0])\n",
    "        if name not in namelist:\n",
    "            now = datetime.now()\n",
    "            dt = now.strftime('%H:%M:%S')\n",
    "            file.writelines(f'\\n{name},{dt}')\n",
    "\n",
    "print(\"Encoding Images...\")\n",
    "encodeList = encode(images)\n",
    "print(\"Encoding Completed.\")\n",
    "\n",
    "#Initializing webcam\n",
    "cap = cv2.VideoCapture(0)\n",
    "\n",
    "while True:\n",
    "    success, img = cap.read()\n",
    "    #Reducing size of real-time image to 1/4th\n",
    "    imgResize = cv2.resize(img, (0,0), None, 0.25, 0.25)\n",
    "    imgResize = cv2.cvtColor(imgResize, cv2.COLOR_BGR2RGB)\n",
    "\n",
    "    # Finding face in current frame\n",
    "    face = face_recognition.face_locations(imgResize)\n",
    "    # Encode detected face\n",
    "    encodeImg = face_recognition.face_encodings(imgResize, face)\n",
    "\n",
    "    #Finding matches with existing images\n",
    "    for encodecurr, loc in zip(encodeImg, face):\n",
    "        match = face_recognition.compare_faces(encodeList, encodecurr)\n",
    "        faceDist = face_recognition.face_distance(encodeList, encodecurr)\n",
    "        print(faceDist)\n",
    "        #Lowest distance will be best match\n",
    "        index_BestMatch = np.argmin(faceDist)\n",
    "\n",
    "        if match[index_BestMatch]:\n",
    "            name = names[index_BestMatch]\n",
    "            y1,x2,y2,x1 = loc\n",
    "            #Retaining original image size for rectangle location\n",
    "            y1,x2,y2,x1 = y1*4, x2*4, y2*4, x1*4\n",
    "            cv2.rectangle(img,(x1,y1),(x2,y2),(255,0,255),1)\n",
    "            cv2.rectangle(img,(x1,y2-30),(x2,y2), (255,0,255), cv2.FILLED)\n",
    "            cv2.putText(img, name, (x1+8, y2-10), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0,255,255),2)\n",
    "            record_attendance(name)\n",
    "\n",
    "    cv2.imshow('Webcam', img)\n",
    "    cv2.waitKey(1)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9913028a",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
